---
name: Release üéà

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build package üéÅ
    needs: release
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      skip-r-cmd-check: true
      skip-r-cmd-install: true
      additional-env-vars: |
        CMDSTAN=/root/.cmdstan
        CMDSTAN_PATH=/root/.cmdstan
        CMDSTANR_NO_VER_CHECK=true
  docs:
    name: Pkgdown Docs üìö
    needs: release
    uses: insightsengineering/r.pkg.template/.github/workflows/pkgdown.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        CMDSTAN=/root/.cmdstan
        CMDSTAN_PATH=/root/.cmdstan
        CMDSTANR_NO_VER_CHECK=true
      default-landing-page: 'latest-tag'
  release:
    name: Create release üéâ
    uses: insightsengineering/r.pkg.template/.github/workflows/release.yaml@main
    permissions:
      contents: write
  r-cmd:
    name: R CMD Check üß¨
    needs: [release, docs]
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        CMDSTAN=/root/.cmdstan
        CMDSTAN_PATH=/root/.cmdstan
        CMDSTANR_NO_VER_CHECK=true
  coverage:
    name: Coverage üìî
    needs: [release, docs]
    uses: insightsengineering/r.pkg.template/.github/workflows/test-coverage.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        CMDSTAN=/root/.cmdstan
        CMDSTAN_PATH=/root/.cmdstan
        CMDSTANR_NO_VER_CHECK=true
